/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fa.gs.empresas.scrapper;

import fa.gs.utils.collections.Sets;
import fa.gs.utils.misc.Assertions;
import fa.gs.utils.misc.errors.Errors;
import fa.gs.utils.misc.text.Strings;
import java.io.FileWriter;
import java.util.Collection;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;

/**
 *
 * @author Fabio A. González Sosa
 */
public class Home extends javax.swing.JFrame {

    public static Home INSTANCE;

    private ExecutorService executor;

    /**
     * Creates new form Main
     */
    public Home() {
        Home.INSTANCE = this;
        this.executor = Executors.newFixedThreadPool(1);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEPSA");
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(64, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("BUSCADOR EMPRESAS - GUÍA INDUSTRIAL COMERCIAL (PY)");

        jLabel2.setText("EMPRESA/RUBRO");

        txtEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpresaActionPerformed(evt);
            }
        });

        jLabel3.setText("CIUDAD");

        txtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 297, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmpresa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(63, 63, 63)
                                .addComponent(txtCiudad))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpresaActionPerformed

    private void txtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        final String empresa = txtEmpresa.getText().trim();
        final String ciudad = txtCiudad.getText().trim();

        logClear();

        executor.submit(() -> {
            try {
                disableUi();
                Collection<Map<String, String>> data = Scrapper.scrap(empresa, ciudad);
                if (!Assertions.isNullOrEmpty(data)) {
                    JFileChooser chooser = new JFileChooser();
                    int ret = chooser.showSaveDialog(null);
                    if (ret == JFileChooser.APPROVE_OPTION) {
                        String filename = chooser.getSelectedFile().getAbsolutePath();
                        if (!filename.endsWith(".csv")) {
                            filename = chooser.getSelectedFile() + ".csv";
                        }
                        try (FileWriter fw = new FileWriter(filename)) {
                            // Claves de cada mapa.
                            Set<String> keys = Sets.empty();
                            for (Map<String, String> entry : data) {
                                keys.addAll(entry.keySet());
                            }

                            // Hack excel.
                            fw.write("SEP=;");
                            fw.write(System.lineSeparator());
                            fw.flush();

                            // Cabecera.
                            Iterator<String> it = keys.iterator();
                            while (true) {
                                fw.write(it.next());
                                if (it.hasNext()) {
                                    fw.write(";");
                                }
                                if (!it.hasNext()) {
                                    break;
                                }
                            }
                            fw.write(System.lineSeparator());
                            fw.flush();

                            // Datos.
                            for (Map<String, String> data0 : data) {
                                it = keys.iterator();
                                while (true) {
                                    fw.write(data0.getOrDefault(it.next(), ""));
                                    if (it.hasNext()) {
                                        fw.write(";");
                                    }
                                    if (!it.hasNext()) {
                                        break;
                                    }
                                }
                                fw.write(System.lineSeparator());
                                fw.flush();
                            }
                        }
                    }
                }
            } catch (Throwable thr) {
                log("Ocurrió un error: %s", Errors.dump(thr));
            } finally {
                enableUi();
                log("Fin.");
            }
        });
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        SwingUtilities.invokeLater(() -> {
            txtEmpresa.setText("");
            txtCiudad.setText("");
            txtLog.setText("");
            txtEmpresa.requestFocus();
        });
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void logClear() {
        SwingUtilities.invokeLater(() -> {
            txtLog.setText("");
        });
    }

    public void log(String fmt, Object... args) {
        final String msg = Strings.format(fmt, args);
        SwingUtilities.invokeLater(() -> {
            String text = txtLog.getText();
            text = text + msg + System.lineSeparator();
            txtLog.setText(text);
        });
    }

    public void enableUi() {
        SwingUtilities.invokeLater(() -> {
            txtEmpresa.setEnabled(true);
            txtCiudad.setEnabled(true);
            btnBuscar.setEnabled(true);
            btnLimpiar.setEnabled(true);
        });
    }

    public void disableUi() {
        SwingUtilities.invokeLater(() -> {
            txtEmpresa.setEnabled(false);
            txtCiudad.setEnabled(false);
            btnBuscar.setEnabled(false);
            btnLimpiar.setEnabled(false);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
